<?php
// $Id: seotools.module,v 1.3 2010/09/26 00:36:50 tomdude48 Exp $

include_once('seotools.features.inc');

/**
 *  Implementation of hook_menu()
 *  
 */
function seotools_menu() {
  $items = array();
  $items['admin/settings/seotools'] = array(
    'title' => 'SEO Tools',
    'description' => 'Analyze and optimize node content.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('seotools_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('admin content analysis'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'seotools.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_presets().
 *
 */
function seotools_presets() {
  include_once(drupal_get_path('module', 'seotools') . '/plugins/seotools.presets.inc');
  return _seotools_presets();
}

function seotools_util() {
  seotools_autotag();
  $output = 'OK';
  return $output;
}

function seotools_autotag() {
  if (module_exists('alchemy')) {
    $usecache = variable_get('seotools_autotag_alchemy_usecache', TRUE);
    $types = variable_get('alchemy_tagging_suggest_types', alchemy_get_types(TRUE));

    $terms = array();
    $r_min = variable_get('seotools_autotag_alchemy_relevance_min', 50) / 100;
    $seotools_uid = variable_get('seotools_uid', 0);

    $page_keyword_obj = new stdClass();
    $page_keyword_obj->priority = 50;
    $page_keyword_obj->uid = $seotools_uid;

    $batch_limit = variable_get('seotools_autotag_batch_limit', 10);
    $sql = '
      SELECT n.nid FROM {node} n
      LEFT JOIN {seotools_node} sn ON sn.nid = n.nid
      WHERE sn.nid is NULL
      LIMIT %d
    ';
    $result = db_query($sql, $batch_limit);
    while($nid = db_result($result)) {
      $node = node_load($nid);
      foreach($types AS $type) {
        $t = alchemy_get_elements_from_node($node, $type, 'normalized', (ALCHEMY_DEBUG || $usecache));
          if(is_array($t)) {
          foreach($t as $k => $v) {
            if($v['relevance'] >= $r_min) {
              //$terms[$k] = $v;
              kwresearch_save_page_keyword($nid, $v['term'], NULL, $page_keyword_obj);
            }
          }
        }
      }
      seotools_save_node_update($node->nid);
    }
  }
}

function seotools_save_node_update($nid) {
  $sql = '
    UPDATE {seotools_node}
    SET updated = %d
    WHERE nid = %d
  ';
  db_query($sql, time(), $nid);
  if(!db_affected_rows()) {
    $sql = '
        INSERT INTO {seotools_node}
        (nid, updated)
        VALUES (%d, %d)
    ';
    db_query($sql, $nid, time());
  }
}

/**
 *  Implementation of hook_cron()
 *  
 */
function seotools_cron() {
  seotools_autotag(); 
}
