<?php
// $Id: seotools.module,v 1.3 2010/09/26 00:36:50 tomdude48 Exp $

include_once('seotools.features.inc');

/**
 *  Implementation of hook_menu()
 *  
 */
function seotools_menu() {
  $items = array();
  $items['admin/settings/seotools'] = array(
    'title' => 'SEO Tools',
    'description' => 'Analyze and optimize node content.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('seotools_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('admin content analysis'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'seotools.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_presets().
 *
 */
function seotools_presets() {
  include_once(drupal_get_path('module', 'seotools') . '/plugins/seotools.presets.inc');
  return _seotools_presets();
}
